### PR TITLE
added yarn and lockfile

### PR DESCRIPTION
**Pull request by rfreitas**

### CODE REVIEW

**Review by stephencookdev — APPROVED** [review]

**Comment by hjheath** [comment]
Do we need to document this?

I don't think it's obvious I should do `yarn install` instead of `npm install`.

How does this work with publishing the package to npm - are the versions pinned there as well?

**Comment by rfreitas** [comment]
sorry, might have gotten ahead of myself.
Yes, we should document that we are using yarn.

For publishing it depends if the consumer uses yarn or not I believe. Let me check.

**Comment by stephencookdev** [comment]
Related to what I was just talking to @rfreitas about offline

I was going to add a `yarn check` to our build pipeline soon, so people get build errors if they used npm directly rather than yarn

And when publishing to npm, as long as your build scripts install with yarn then they will be fixed before being autobundled (and anyone checking out the repo will get the pinned versions, as long as they do so with yarn).

**Comment by rfreitas** [comment]
there is a `yarn publish`. I don't know if it's necessary to include `yarn.lock` in the `package.json` `"files":[...]`.

do you know if that is the case, @stephencookdev ?

**Comment by stephencookdev** [comment]
Shouldn't be - you're publishing the built code, right? No sense including config on locking down versions on built (and thus already locked) code

**Comment by rfreitas** [comment]
not just. we also publish unbundled code, to be used with `require` or `import`.

It's actually quite messy and needs to be cleaned up. the bundled `core` is never used I believe.

**Comment by rfreitas** [comment]
As a summary, yarn on core doesn't make a huge difference, since it's being used as a non bundled package. Which means who ever uses it, will have its own yarn lock, locking down sdk-core dependencies.

It's beneficial mostly for dev dependencies.

**Pull request merged**
